mqtt:
  sensor:
    - name: "Garagentor"
      state_topic: "homeassistant/cover/state"
      value_template: >-
        {% if value == "open" %}
          Offen
        {% elif value == "closed" %}
          Geschlossen
        {% elif value == "venting" %}
          Lüfterstellung
        {% elif value == "opening" %}
          Fährt auf
        {% elif value == "closing" %}
          Fährt zu
        {% elif value == "error" %}
          Fehler
        {% elif value == "offline" %}
          Offline
        {% else %}
          Gestoppt
        {% endif %}
      state_class: measurement
    - name: "Temperatur Garage"
      state_topic: "homeassistant/sensor/garage/value"
      value_template: "{{ value_json.temperature_C | round(1) }}"
      unit_of_measurement: '°C'
      state_class: measurement
      device_class: temperature
    - name: "Feuchtigkeit Garage"
      state_topic: "homeassistant/sensor/garage/value"
      value_template: "{{ value_json.humidity | round(0) }}"
      unit_of_measurement: '%'
      state_class: measurement
      device_class: humidity
    - name: "Luftdruck Garage"
      state_topic: "homeassistant/sensor/garage/value"
      value_template: "{{ value_json.pressure_hPa | round(1) }}"
      unit_of_measurement: 'hPa'
      state_class: measurement
      device_class: pressure
  cover:
    - name: "Garagentor"
      command_topic: "homeassistant/cover/set"
      position_topic: "homeassistant/cover/state"
      qos: 0
      retain: false
      payload_open: "OPEN"
      payload_close: "CLOSE"
      payload_stop: "STOP"
      position_open: 100
      position_closed: 0
      position_template: >-
        {% if value == "open" %}100{% elif value == "closed" %}0{% else %}10{% endif %}
      device_class: garage
  switch:
    - name: "Lüfterstellung"
      command_topic: "homeassistant/cover/set"
      state_topic: "homeassistant/cover/state"
      qos: 0
      retain: false
      payload_on: "VENTING"
      payload_off: "CLOSE"
      state_on : "ON"
      state_off : "OFF"
      value_template: >-
        {% if value == "venting" %}ON{% else %}OFF{% endif %}
