# These substitutions allow the end user to override certain values
substitutions:
  name: "promatic-e4"
  friendly_name: "ProMatic E4"
  state: "State"
  opening: "Opening"
  closing: "Closing"
  open: "Open"
  closed: "Closed"
  stopped: "Stopped"
  venting: "Venting"
  halfopen: "Half open"
  relay_state: "Relay state"
  is_connected: "Valid Status received"
  light: "${friendly_name} Light"
  sw_vent: "${friendly_name} Venting"
  sw_half: "${friendly_name} Half open"
  sw_light: "Switch Light"
  btn_vent: "${friendly_name} Vent"
  btn_impulse: "${friendly_name} Impulse"
  btn_half: "${friendly_name} Half open"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

external_components:
    - source: github://14yannick/hoermann_door
      refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key_e4_hcp

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: WARN
  baud_rate: 0 # Disable Serial logging to avoid conflict with uart bus

uart:
  id: uart_bus
  baud_rate: 57600
  parity: EVEN
  rx_pin: 16
  tx_pin: 17
  # rts_pin: 4 # uncomment if your RS485 transceiver requires direction control

uapbridge_hcp:
  id: garage_door_comp
  uart_id: uart_bus
  # high_frequency_loop: false # uncomment to disable if CPU usage needs to be reduced

cover:
  - platform: uapbridge
    name: ${friendly_name}
    device_class: garage

switch:
  - platform: uapbridge
    venting_switch:
      id: venting_switch
      name: "${sw_vent}"
    half_switch:
      id: half_switch
      name: "${sw_half}"
#uncomment if you want to use the switch instead of the light component for light
#    light_switch:
#      id: light_switch
#      name: "${sw_light}"

binary_sensor:
  - platform: uapbridge
    relay_state:
      name: "${relay_state}"
    is_connected:
      name: "${is_connected}"

output:
  - platform: uapbridge
    id: gd_light

light:
  - platform: uapbridge
    id: my_light
    name: "${light}"
    output: gd_light

text_sensor:
  - platform: uapbridge
    id: garage_door_state
    name: "${state}"
#    filters:
#      - substitute:
#        - "Opening -> ${opening}"
#        - "Closing -> ${closing}"
#        - "Open -> ${open}"
#        - "Closed -> ${closed}"
#        - "Stopped -> ${stopped}"
#        - "Venting -> ${venting}"
#        - "Half open -> ${halfopen}"

button:
  - platform: uapbridge
    vent_button:
      id: button_vent
      name: "${btn_vent}"
    impulse_button:
      id: button_impulse
      name: "${btn_impulse}"
    half_button:
      id: button_half
      name: "${btn_half}"

